spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai
    username: root
    password: wanghongyu
server:
  port: 8888

#配置mybatis-plus 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config: #配置逻辑删除
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0